try{
'use strict';var l,n=this,p=function(a){a.p=function(){return a.N?a.N:a.N=new a}},aa=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&
"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},r=function(a){return"array"==aa(a)},u=function(a){return"string"==typeof a},ba=function(a){return"function"==aa(a)},ca=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b},fa=function(a){return a[da]||(a[da]=++ea)},da="closure_uid_"+(1E9*Math.random()>>>0),ea=0,ga=function(a,b,c){return a.call.apply(a.bind,
arguments)},ha=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},w=function(a,b,c){w=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ga:ha;return w.apply(null,arguments)},ia=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=
c.slice();b.push.apply(b,arguments);return a.apply(this,b)}},x=Date.now||function(){return+new Date},y=function(a,b){function c(){}c.prototype=b.prototype;a.A=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.V=function(a,c,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[c].apply(a,g)}};
var z=function(){this.e=this.e;this.c=this.c};z.prototype.e=!1;z.prototype.M=function(){this.e||(this.e=!0,this.v())};var ja=function(a,b){a.e?b.call(void 0):(a.c||(a.c=[]),a.c.push(b))};z.prototype.v=function(){if(this.c)for(;this.c.length;)this.c.shift()()};var ka=function(a){a&&"function"==typeof a.M&&a.M()};
var A=function(a,b){this.type=a;this.a=this.target=b;this.P=!0};A.prototype.d=function(){this.P=!1};var la=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},na=function(a){var b={"&amp;":"&","&lt;":"<","&gt;":">","&quot;":'"'},c;c=n.document.createElement("div");return a.replace(ma,function(a,e){var f=b[a];if(f)return f;if("#"==e.charAt(0)){var g=Number("0"+e.substr(1));isNaN(g)||(f=String.fromCharCode(g))}f||(c.innerHTML=a+" ",f=c.firstChild.nodeValue.slice(0,-1));return b[a]=f})},oa=function(a){return a.replace(/&([^;]+);/g,function(a,
c){switch(c){case "amp":return"&";case "lt":return"<";case "gt":return">";case "quot":return'"';default:if("#"==c.charAt(0)){var d=Number("0"+c.substr(1));if(!isNaN(d))return String.fromCharCode(d)}return a}})},ma=/&([^;\s<&]+);?/g,B=function(a){return null==a?"":String(a)},pa=function(a,b){return a<b?-1:a>b?1:0},qa=function(a){isFinite(a)&&(a=String(a));return u(a)?/^\s*-?0x/i.test(a)?parseInt(a,16):parseInt(a,10):NaN};
var ra=function(a){A.call(this,a);this.e=0;this.c=null;this.h=this.i="";this.k=0;this.g=""};y(ra,A);var sa=function(a,b,c,d,e){var f=new ra("clip_changed");f.c=a;f.e=b;f.i=c;f.h=d;e&&(f.k=e.h,f.g=e.o());return f};ra.prototype.B=function(){return B(this.c&&this.c.o()||null)};
var ta;var C=Array.prototype,ua=C.indexOf?function(a,b,c){return C.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(u(a))return u(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},va=C.forEach?function(a,b,c){C.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=u(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},wa=C.filter?function(a,b,c){return C.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=u(a)?
a.split(""):a,h=0;h<d;h++)if(h in g){var k=g[h];b.call(c,k,h,a)&&(e[f++]=k)}return e},xa=C.map?function(a,b,c){return C.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=u(a)?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e},ya=function(a){return C.concat.apply(C,arguments)},za=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]},Aa=function(a,b){for(var c=b||function(){return ca(g)?"o"+fa(g):(typeof g).charAt(0)+g},d={}, e=0,f=0;f<a.length;){var g=a[f++],h=c(g);Object.prototype.hasOwnProperty.call(d,h)||(d[h]=!0,a[e++]=g)}a.length=e},Ba=function(a,b){return a>b?1:a<b?-1:0};
var Ca=n.JSON.stringify;var Da=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)},Ea=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b},Fa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),Ga=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Fa.length;f++)c=Fa[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}},Ha=function(a){var b=arguments.length;if(1==b&&r(arguments[0]))return Ha.apply(null, arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c};
var D=function(){},E=function(a,b,c,d){a.a=null;b||(b=[]);a.h=void 0;a.g=-1;a.c=b;a:{if(a.c.length){b=a.c.length-1;var e=a.c[b];if(e&&"object"==typeof e&&!r(e)){a.e=b-a.g;a.d=e;break a}}-1<c?(a.e=c,a.d=null):a.e=Number.MAX_VALUE}if(d)for(c=0;c<d.length;c++)b=d[c],b<a.e?(b+=a.g,a.c[b]=a.c[b]||Ia):a.d[b]=a.d[b]||Ia},Ia=[],F=function(a,b){if(b<a.e){var c=b+a.g,d=a.c[c];return d===Ia?a.c[c]=[]:d}d=a.d[b];return d===Ia?a.d[b]=[]:d},G=function(a,b,c){b<a.e?a.c[b+a.g]=c:a.d[b]=c},H=function(a,b,c){a.a||
(a.a={});if(!a.a[c]){var d=F(a,c);d&&(a.a[c]=new b(d))}return a.a[c]},I=function(a,b,c){a.a||(a.a={});var d=c?c.c:c;a.a[b]=c;G(a,b,d)};D.prototype.l=function(){return n.JSON&&n.JSON.stringify?n.JSON.stringify(this.c):Ca(this.c)};D.prototype.toString=function(){return this.c.toString()};
var Ka=function(a){var b=Ja;if(a.d){a.a||(a.a={});var c=b.c;if(b.d){if(b.a)return a.a[c]||(a.a[c]=xa(a.d[c]||[],function(a){return new b.a(a)})),a.a[c]}else if(b.a)return!a.a[c]&&a.d[c]&&(a.a[c]=new b.a(a.d[c])),a.a[c];return a.d[c]}},La=function(a){var b;if(r(a)){for(var c=Array(a.length),d=0;d<a.length;d++)null!=(b=a[d])&&(c[d]="object"==typeof b?La(b):b);return c}c={};for(d in a)null!=(b=a[d])&&(c[d]="object"==typeof b?La(b):b);return c};
var Ma=function(a){E(this,a,-1,null)};y(Ma,D);var J=function(a){return H(a,Na,2)},Na=function(a){E(this,a,-1,null)};y(Na,D);var Oa=function(a){return F(a,1)};var Pa=function(a){E(this,a,-1,null)};y(Pa,D);Pa.prototype.o=function(){return F(this,1)};var Qa=function(a){E(this,a,-1,null)};y(Qa,D);Qa.prototype.getTitle=function(){return F(this,1)};Qa.prototype.setTitle=function(a){G(this,1,a)};var Ra=function(a){E(this,a,-1,null)};y(Ra,D);var Sa=function(a){E(this,a,-1,null)};y(Sa,D);var Ua=function(a){E(this,a,22,Ta)};y(Ua,D);var Ta=[3];Ua.prototype.B=function(){return H(this,Pa,1)};var Va=function(a){E(this,a,-1,null)};y(Va,D);var Wa=function(a){this.a=a||new Va};Wa.prototype.l=function(){return this.a.l()};var Xa;a:{var Ya=n.navigator;if(Ya){var Za=Ya.userAgent;if(Za){Xa=Za;break a}}Xa=""}var K=function(a){return-1!=Xa.indexOf(a)};var $a=function(){return K("Opera")||K("OPR")},ab=function(){return K("Edge")||K("Trident")||K("MSIE")},bb=function(){return(K("Chrome")||K("CriOS"))&&!$a()&&!ab()};var L=function(){return K("Edge")};var cb=$a(),M=ab(),db=K("Gecko")&&!(-1!=Xa.toLowerCase().indexOf("webkit")&&!L())&&!(K("Trident")||K("MSIE"))&&!L(),eb=-1!=Xa.toLowerCase().indexOf("webkit")&&!L(),fb=function(){var a=Xa;if(db)return/rv\:([^\);]+)(\)|;)/.exec(a);if(M&&L())return/Edge\/([\d\.]+)/.exec(a);if(M)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(eb)return/WebKit\/(\S+)/.exec(a)},gb=function(){var a=n.document;return a?a.documentMode:void 0},ib=function(){if(cb&&n.opera){var a=n.opera.version;return ba(a)?a():a}var a=
"",b=fb();b&&(a=b?b[1]:"");return M&&!L()&&(b=gb(),b>parseFloat(a))?String(b):a}(),jb={},N=function(a){var b;if(!(b=jb[a])){b=0;for(var c=la(String(ib)).split("."),d=la(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"",k=/(\d*)(\D*)/g,q=/(\d*)(\D*)/g;do{var m=k.exec(g)||["","",""],t=q.exec(h)||["","",""];if(0==m[0].length&&0==t[0].length)break;b=pa(0==m[1].length?0:parseInt(m[1],10),0==t[1].length?0:parseInt(t[1],10))||pa(0==m[2].length,0==t[2].length)|| pa(m[2],t[2])}while(0==b)}b=jb[a]=0<=b}return b},kb=n.document,lb=gb(),mb=!kb||!M||!lb&&L()?void 0:lb||("CSS1Compat"==kb.compatMode?parseInt(ib,10):5);
var nb=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/,qb=function(a){if(ob){ob=!1;var b=n.location;if(b){var c=b.href;if(c&&(c=pb(qb(c)[3]||null))&&c!=b.hostname)throw ob=!0,Error();}}return a.match(nb)},ob=eb,pb=function(a){return a?decodeURI(a):a},rb=function(a,b){for(var c=a.split("&"),d=0;d<c.length;d++){var e=c[d].indexOf("="),f=null,g=null;0<=e?(f=c[d].substring(0,e),g=c[d].substring(e+1)):f=c[d];b(f,g?decodeURIComponent(g.replace(/\+/g, " ")):"")}};
var sb="StopIteration"in n?n.StopIteration:Error("StopIteration"),tb=function(){};tb.prototype.next=function(){throw sb;};tb.prototype.I=function(){return this};var O=function(a,b){this.c={};this.a=[];this.e=this.d=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){if(a instanceof O)d=a.C(),c=a.m();else{var c=[],e=0;for(d in a)c[e++]=d;d=c;c=Ea(a)}for(e=0;e<d.length;e++)this.set(d[e],c[e])}};O.prototype.m=function(){ub(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.c[this.a[b]]);return a};O.prototype.C=function(){ub(this);return this.a.concat()};
O.prototype.D=function(){return 0==this.d};O.prototype.remove=function(a){return vb(this.c,a)?(delete this.c[a],this.d--,this.e++,this.a.length>2*this.d&&ub(this),!0):!1};var ub=function(a){if(a.d!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];vb(a.c,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.d!=a.a.length){for(var e={},c=b=0;b<a.a.length;)d=a.a[b],vb(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}};l=O.prototype;l.get=function(a,b){return vb(this.c,a)?this.c[a]:b};
l.set=function(a,b){vb(this.c,a)||(this.d++,this.a.push(a),this.e++);this.c[a]=b};l.forEach=function(a,b){for(var c=this.C(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};l.clone=function(){return new O(this)};l.I=function(a){ub(this);var b=0,c=this.e,d=this,e=new tb;e.next=function(){if(c!=d.e)throw Error("The map has changed since the iterator was created");if(b>=d.a.length)throw sb;var e=d.a[b++];return a?e:d.c[e]};return e}; var vb=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
var wb=function(a){if("function"==typeof a.m)return a.m();if(u(a))return a.split("");var b=aa(a);if("array"==b||"object"==b&&"number"==typeof a.length){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Ea(a)};var P=function(a,b){this.c=this.i=this.d="";this.k=null;this.e=this.a="";this.g=!1;var c;a instanceof P?(this.g=void 0!==b?b:a.g,xb(this,a.d),this.i=a.i,this.c=a.c,yb(this,a.k),this.a=a.a,zb(this,a.h.clone()),this.e=a.e):a&&(c=qb(String(a)))?(this.g=!!b,xb(this,c[1]||"",!0),this.i=Ab(c[2]||""),this.c=Ab(c[3]||"",!0),yb(this,c[4]),this.a=Ab(c[5]||"",!0),zb(this,c[6]||"",!0),this.e=Ab(c[7]||"")):(this.g=!!b,this.h=new Q(null,0,this.g))};
P.prototype.toString=function(){var a=[],b=this.d;b&&a.push(Bb(b,Cb,!0),":");if(b=this.c){a.push("//");var c=this.i;c&&a.push(Bb(c,Cb,!0),"@");a.push(encodeURIComponent(String(b)).replace(/%25([0-9a-fA-F]{2})/g,"%$1"));b=this.k;null!=b&&a.push(":",String(b))}if(b=this.a)this.c&&"/"!=b.charAt(0)&&a.push("/"),a.push(Bb(b,"/"==b.charAt(0)?Db:Eb,!0));(b=this.h.toString())&&a.push("?",b);(b=this.e)&&a.push("#",Bb(b,Fb));return a.join("")};P.prototype.clone=function(){return new P(this)};
var xb=function(a,b,c){a.d=c?Ab(b,!0):b;a.d&&(a.d=a.d.replace(/:$/,""))},yb=function(a,b){if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.k=b}else a.k=null},zb=function(a,b,c){b instanceof Q?(a.h=b,Gb(a.h,a.g)):(c||(b=Bb(b,Hb)),a.h=new Q(b,0,a.g))},Ib=function(a){return a instanceof P?a.clone():new P(a,void 0)},Ab=function(a,b){return a?b?decodeURI(a):decodeURIComponent(a):""},Bb=function(a,b,c){return u(a)?(a=encodeURI(a).replace(b,Jb),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,
"%$1")),a):null},Jb=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},Cb=/[#\/\?@]/g,Eb=/[\#\?:]/g,Db=/[\#\?]/g,Hb=/[\#\?@]/g,Fb=/#/g,Q=function(a,b,c){this.d=this.a=null;this.c=a||null;this.e=!!c},R=function(a){a.a||(a.a=new O,a.d=0,a.c&&rb(a.c,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))};Q.prototype.add=function(a,b){R(this);this.c=null;a=Kb(this,a);var c=this.a.get(a);c||this.a.set(a,c=[]);c.push(b);this.d++;return this};
Q.prototype.remove=function(a){R(this);a=Kb(this,a);return vb(this.a.c,a)?(this.c=null,this.d-=this.a.get(a).length,this.a.remove(a)):!1};Q.prototype.D=function(){R(this);return 0==this.d};var Lb=function(a,b){R(a);b=Kb(a,b);return vb(a.a.c,b)};l=Q.prototype;l.C=function(){R(this);for(var a=this.a.m(),b=this.a.C(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};
l.m=function(a){R(this);var b=[];if(u(a))Lb(this,a)&&(b=ya(b,this.a.get(Kb(this,a))));else{a=this.a.m();for(var c=0;c<a.length;c++)b=ya(b,a[c])}return b};l.set=function(a,b){R(this);this.c=null;a=Kb(this,a);Lb(this,a)&&(this.d-=this.a.get(a).length);this.a.set(a,[b]);this.d++;return this};l.get=function(a,b){var c=a?this.m(a):[];return 0<c.length?String(c[0]):b};
l.toString=function(){if(this.c)return this.c;if(!this.a)return"";for(var a=[],b=this.a.C(),c=0;c<b.length;c++)for(var d=b[c],e=encodeURIComponent(String(d)),d=this.m(d),f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+encodeURIComponent(String(d[f])));a.push(g)}return this.c=a.join("&")};l.clone=function(){var a=new Q;a.c=this.c;this.a&&(a.a=this.a.clone(),a.d=this.d);return a};
var Kb=function(a,b){var c=String(b);a.e&&(c=c.toLowerCase());return c},Gb=function(a,b){b&&!a.e&&(R(a),a.c=null,a.a.forEach(function(a,b){var e=b.toLowerCase();b!=e&&(this.remove(b),this.remove(e),0<a.length&&(this.c=null,this.a.set(Kb(this,e),za(a)),this.d+=a.length))},a));a.e=b};
var Mb=function(a){this.a=a||new Qa;a=F(this.a,3);G(this.a,3,a)};Mb.prototype.getTitle=function(){return B(this.a.getTitle())};Mb.prototype.setTitle=function(a){this.a.setTitle(a)};Mb.prototype.l=function(){return this.a.l()};Ha("area base br col command embed hr img input keygen link meta param source track wbr".split(" "));var Nb=function(){this.c="";this.a=null},Ob=function(a){var b=new Nb;b.c=a;b.a=0};Ob("<!DOCTYPE html>");Ob("");var Pb=function(a){this.a=new O;if(a){a=wb(a);for(var b=a.length,c=0;c<b;c++)this.add(a[c])}},Qb=function(a){var b=typeof a;return"object"==b&&a||"function"==b?"o"+fa(a):b.substr(0,1)+a};l=Pb.prototype;l.add=function(a){this.a.set(Qb(a),a)};l.removeAll=function(a){a=wb(a);for(var b=a.length,c=0;c<b;c++)this.remove(a[c])};l.remove=function(a){return this.a.remove(Qb(a))};l.D=function(){return this.a.D()};l.m=function(){return this.a.m()};l.clone=function(){return new Pb(this)};l.I=function(){return this.a.I(!1)};
var Rb=function(a,b,c,d,e){this.reset(a,b,c,d,e)};Rb.prototype.a=null;var Sb=0;Rb.prototype.reset=function(a,b,c,d,e){"number"==typeof e||Sb++;this.d=d||x();this.e=a;this.g=b;this.c=c;delete this.a};Rb.prototype.getMessage=function(){return this.g};var Tb=function(a){this.e=a;this.c=this.d=this.a=null},Ub=function(a,b){this.name=a;this.value=b};Ub.prototype.toString=function(){return this.name};var Vb=new Ub("SHOUT",1200),Wb=new Ub("SEVERE",1E3),Xb=new Ub("WARNING",900),Yb=new Ub("INFO",800),Zb=new Ub("CONFIG",700);Tb.prototype.getChildren=function(){this.c||(this.c={});return this.c};var $b=function(a){return a.d?a.d:a.a?$b(a.a):null};
Tb.prototype.log=function(a,b,c){if(a.value>=$b(this).value)for(ba(b)&&(b=b()),a=new Rb(a,String(b),this.e),c&&(a.a=c),c="log:"+a.getMessage(),n.console&&(n.console.timeStamp?n.console.timeStamp(c):n.console.markTimeline&&n.console.markTimeline(c)),n.msWriteProfilerMark&&n.msWriteProfilerMark(c),c=this;c;)c=c.a}; var cc={},dc=null,ec=function(){dc||(dc=new Tb(""),cc[""]=dc,dc.d=Zb)},S=function(a){ec();var b;if(!(b=cc[a])){b=new Tb(a);var c=a.lastIndexOf("."),d=a.substr(c+1),c=S(a.substr(0,c));c.getChildren()[d]=b;b.a=c;cc[a]=b}return b};
!K("Android")||bb()||K("Firefox")||$a();bb();S("gws.collections.models.IndexedClips");S("gws.collections.models.IndexedFolios");var fc=function(){};p(fc);var gc={0:"c_",1:"f_",2:"d_",3:"g_",4:"lc_",5:"lf_"},hc=function(a){return gc[a]+(839808*a+Math.floor(839808*Math.random())).toString(36)+x().toString(36)};var ic=function(a,b,c){A.call(this,c||"TRANSACTION_COMMIT");this.h=a||0;(a=b)||(fc.p(),a=hc(2));this.g=a;this.c=[];this.e=[]};y(ic,A);ic.prototype.o=function(){return this.g};var jc=!M||M&&(L()||9<=mb),kc=M&&!N("9");!eb||N("528");db&&N("1.9b")||M&&N("8")||cb&&N("9.5")||eb&&N("528");db&&!N("8")||M&&N("9");var lc=function(a){lc[" "](a);return a};lc[" "]=function(){};var mc=function(a,b){A.call(this,a?a.type:"");this.a=this.target=null;this.clientY=this.clientX=0;this.c=this.state=null;if(a){this.type=a.type;this.target=a.target||a.srcElement;this.a=b;var c=a.relatedTarget;if(c&&db)try{lc(c.nodeName)}catch(d){}this.clientX=void 0!==a.clientX?a.clientX:a.pageX;this.clientY=void 0!==a.clientY?a.clientY:a.pageY;this.state=a.state;this.c=a;a.defaultPrevented&&this.d()}};y(mc,A); mc.prototype.d=function(){mc.A.d.call(this);var a=this.c;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,kc)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
var nc="closure_listenable_"+(1E6*Math.random()|0),oc=function(a){return!(!a||!a[nc])},pc=0;var qc=function(a,b,c,d,e){this.w=a;this.proxy=null;this.src=b;this.type=c;this.G=!!d;this.H=e;this.J=++pc;this.removed=this.F=!1},rc=function(a){a.removed=!0;a.w=null;a.proxy=null;a.src=null;a.H=null};var sc=function(a){this.src=a;this.a={};this.c=0};sc.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.c++);var g=tc(a,b,d,e);-1<g?(b=a[g],c||(b.F=!1)):(b=new qc(b,this.src,f,!!d,e),b.F=c,a.push(b));return b};sc.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=tc(e,b,c,d);return-1<b?(rc(e[b]),C.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.c--),!0):!1};
var uc=function(a,b){var c=b.type;if(!(c in a.a))return!1;var d=a.a[c],e=ua(d,b),f;(f=0<=e)&&C.splice.call(d,e,1);f&&(rc(b),0==a.a[c].length&&(delete a.a[c],a.c--));return f};sc.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,rc(d[e]);delete this.a[c];this.c--}return b}; var vc=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=tc(a,c,d,e));return-1<b?a[b]:null},tc=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.w==b&&f.G==!!c&&f.H==d)return e}return-1};
var wc="closure_lm_"+(1E6*Math.random()|0),xc={},yc=0,zc=function(a,b,c,d,e){if(r(b)){for(var f=0;f<b.length;f++)zc(a,b[f],c,d,e);return null}c=Ac(c);return oc(a)?a.listen(b,c,d,e):Bc(a,b,c,!1,d,e)},Bc=function(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var g=!!e,h=Cc(a);h||(a[wc]=h=new sc(a));c=h.add(b,c,d,e,f);if(c.proxy)return c;d=Dc();c.proxy=d;d.src=a;d.w=c;a.addEventListener?a.addEventListener(b.toString(),d,g):a.attachEvent(Ec(b.toString()),d);yc++;return c},Dc=function(){var a=Fc,
b=jc?function(c){return a.call(b.src,b.w,c)}:function(c){c=a.call(b.src,b.w,c);if(!c)return c};return b},Gc=function(a,b,c,d,e){if(r(b)){for(var f=0;f<b.length;f++)Gc(a,b[f],c,d,e);return null}c=Ac(c);return oc(a)?a.n.add(String(b),c,!0,d,e):Bc(a,b,c,!0,d,e)},Hc=function(a,b,c,d,e){if(r(b))for(var f=0;f<b.length;f++)Hc(a,b[f],c,d,e);else c=Ac(c),oc(a)?a.unlisten(b,c,d,e):a&&(a=Cc(a))&&(b=vc(a,b,c,!!d,e))&&Ic(b)},Ic=function(a){if("number"==typeof a||!a||a.removed)return!1;var b=a.src;if(oc(b))return uc(b.n,
a);var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.G):b.detachEvent&&b.detachEvent(Ec(c),d);yc--;(c=Cc(b))?(uc(c,a),0==c.c&&(c.src=null,b[wc]=null)):rc(a);return!0},Ec=function(a){return a in xc?xc[a]:xc[a]="on"+a},Kc=function(a,b,c,d){var e=!0;if(a=Cc(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.G==c&&!f.removed&&(f=Jc(f,d),e=e&&!1!==f)}return e},Jc=function(a,b){var c=a.w,d=a.H||a.src;a.F&&Ic(a);return c.call(d,b)},Fc=function(a,b){if(a.removed)return!0;
if(!jc){var c;if(!(c=b))a:{c=["window","event"];for(var d=n,e;e=c.shift();)if(null!=d[e])d=d[e];else{c=null;break a}c=d}e=c;c=new mc(e,this);d=!0;if(!(0>e.keyCode||void 0!=e.returnValue)){a:{var f=!1;if(0==e.keyCode)try{e.keyCode=-1;break a}catch(g){f=!0}if(f||void 0==e.returnValue)e.returnValue=!0}e=[];for(f=c.a;f;f=f.parentNode)e.push(f);for(var f=a.type,h=e.length-1;0<=h;h--){c.a=e[h];var k=Kc(e[h],f,!0,c),d=d&&k}for(h=0;h<e.length;h++)c.a=e[h],k=Kc(e[h],f,!1,c),d=d&&k}return d}return Jc(a,new mc(b, this))},Cc=function(a){a=a[wc];return a instanceof sc?a:null},Lc="__closure_events_fn_"+(1E9*Math.random()>>>0),Ac=function(a){if(ba(a))return a;a[Lc]||(a[Lc]=function(b){return a.handleEvent(b)});return a[Lc]};
var T=function(){z.call(this);this.n=new sc(this);this.R=this;this.g=null};y(T,z);T.prototype[nc]=!0;l=T.prototype;l.addEventListener=function(a,b,c,d){zc(this,a,b,c,d)};l.removeEventListener=function(a,b,c,d){Hc(this,a,b,c,d)};
l.s=function(a){var b,c=this.g;if(c)for(b=[];c;c=c.g)b.push(c);var c=this.R,d=a.type||a;if(u(a))a=new A(a,c);else if(a instanceof A)a.target=a.target||c;else{var e=a;a=new A(d,c);Ga(a,e)}var e=!0,f;if(b)for(var g=b.length-1;0<=g;g--)f=a.a=b[g],e=Mc(f,d,!0,a)&&e;f=a.a=c;e=Mc(f,d,!0,a)&&e;e=Mc(f,d,!1,a)&&e;if(b)for(g=0;g<b.length;g++)f=a.a=b[g],e=Mc(f,d,!1,a)&&e;return e};l.v=function(){T.A.v.call(this);this.n&&this.n.removeAll(void 0);this.g=null};
l.listen=function(a,b,c,d){return this.n.add(String(a),b,!1,c,d)};l.unlisten=function(a,b,c,d){return this.n.remove(String(a),b,c,d)};var Mc=function(a,b,c,d){b=a.n.a[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var g=b[f];if(g&&!g.removed&&g.G==c){var h=g.w,k=g.H||g.src;g.F&&uc(a.n,g);e=!1!==h.call(k,d)&&e}}return e&&0!=d.P};
var Nc=function(){T.call(this)};y(Nc,T);var Oc=function(a){T.call(this);this.a=a};y(Oc,Nc);Oc.prototype.o=function(){return this.a.B()?B(this.a.B().o()):""};Oc.prototype.l=function(){return this.a.l()};var Pc=".0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz".split(""),Qc={},Rc;for(Rc in Pc)Qc[Pc[Rc]]=Rc;for(var Sc in Qc);var U=function(a){z.call(this);this.d=a;this.a={}};y(U,z);var Tc=[];U.prototype.listen=function(a,b,c,d){r(b)||(b&&(Tc[0]=b.toString()),b=Tc);for(var e=0;e<b.length;e++){var f=zc(a,b[e],c||this.handleEvent,d||!1,this.d||this);if(!f)break;this.a[f.J]=f}return this};var Uc=function(a,b,c,d,e,f){if(r(c))for(var g=0;g<c.length;g++)Uc(a,b,c[g],d,e,f);else(b=Gc(b,c,d||a.handleEvent,e,f||a.d||a))&&(a.a[b.J]=b)};
U.prototype.unlisten=function(a,b,c,d,e){if(r(b))for(var f=0;f<b.length;f++)this.unlisten(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.d||this,c=Ac(c),d=!!d,b=oc(a)?vc(a.n,String(b),c,d,e):a?(a=Cc(a))?vc(a,b,c,d,e):null:null,b&&(Ic(b),delete this.a[b.J]);return this};U.prototype.removeAll=function(){Da(this.a,Ic);this.a={}};U.prototype.v=function(){U.A.v.call(this);this.removeAll()};U.prototype.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};
var V=function(a,b){this.width=a;this.height=b};V.prototype.clone=function(){return new V(this.width,this.height)};var Vc=function(a){return a.width*a.height};V.prototype.D=function(){return!Vc(this)};V.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
var Wc=function(a){this.a=a||new Ma;if(!J(this.a)){a=this.a;var b=new Na;I(a,2,b)}H(this.a,Na,3)||(a=this.a,b=new Na,I(a,3,b));this.c=new P(B(Oa(J(this.a))));new P(B(Oa(H(this.a,Na,3))).replace(/^\/\//,"https://"))};Wc.prototype.l=function(){return this.a.l()};
var Xc=function(a){this.a=a||new Ra};Xc.prototype.l=function(){return this.a.l()};var Yc=function(a){this.a=a||new Sa};Yc.prototype.l=function(){return this.a.l()};var Zc=function(a){E(this,a,-1,null)};y(Zc,D);var Ja=new function(){this.c=71309500;this.a=Zc;this.d=0}(function(a,b){var c,d=F(b,1),e=F(b,2),f;if(f=c=b.getLocation())f={latitude:F(c,1),longitude:F(c,2)},a&&(f.Q=c);c={W:d,X:e,location:f};a&&(c.Q=b);return c});Zc.prototype.getLocation=function(){return H(this,$c,3)};var $c=function(a){E(this,a,-1,null)};y($c,D);
var W=function(a){Oc.call(this,a||new Ua);this.d=ad(this);this.h=bd(this);a=this.a;a.a||(a.a={});if(!a.a[3]){for(var b=F(a,3),c=[],d=0;d<b.length;d++)c[d]=new Va(b[d]);a.a[3]=c}b=a.a[3];b==Ia&&(b=a.a[3]=[]);a=b;for(b=0;b<a.length;b++)c=new Wa(a[b]),H(c.a,Pa,1).o();a=H(this.a,Sa,10);!this.i&&a&&(this.i=new Yc(a));this.i=this.i||null;a=H(this.a,Ra,13);!this.k&&a&&(this.k=new Xc(a));this.k=this.k||null;new Pb;this.o()||(fc.p(),a=hc(0),this.a.B()||(b=new Pa,I(this.a,1,b)),b=this.a.B(),G(b,1,a))};
y(W,Oc);S("gws.collections.models.ClipModel");W.prototype.clone=function(){var a;a=this.a;a=new a.constructor(La(a.c));return new W(a)};var ad=function(a){var b=H(a.a,Ma,5);!a.d&&b&&(a.d=new Wc(b));return a.d||null},bd=function(a){var b=H(a.a,Qa,6);!a.h&&b&&(a.h=new Mb(b));return a.h||null};W.prototype.getTitle=function(){return bd(this)?bd(this).getTitle().toString():""};
W.prototype.setTitle=function(a,b){var c=b||new ic;if(bd(this).getTitle()==a)return!1;var d=bd(this).l(),e=bd(this);e.setTitle(a);var f=x();G(this.a,8,f);d=sa(this,204,d,e.l(),c);c.c.push(d);c.e.push(this);this.s(d);c!=b&&0<c.c.length&&this.s(c);return!0};var cd=function(a,b){var c=new ic,d=F(a.a,4);F(a.a,4)!=b&&(G(a.a,4,b),d=sa(a,206,""+d,""+b,c),c.c.push(d),c.e.push(a),a.s(d),void 0!=c&&0<c.c.length&&a.s(c))};W.prototype.toString=function(){return"ClipModel:"+this.o()}; W.prototype.getLocation=function(){var a=Ka(this.a);return a&&(a=a.getLocation())?B(F(a,1).toFixed(4)+","+F(a,2).toFixed(4)):""};
var dd=!db&&!M||M&&M&&(L()||9<=mb)||db&&N("1.9.1"),ed=M&&!N("9"),fd=M||cb||eb;var gd=function(a,b){this.x=void 0!==a?a:0;this.y=void 0!==b?b:0};gd.prototype.clone=function(){return new gd(this.x,this.y)};gd.prototype.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};var hd=function(a){return dd&&void 0!=a.children?a.children:wa(a.childNodes,function(a){return 1==a.nodeType})},id=function(a){var b;if(fd&&!(M&&N("9")&&!N("10")&&n.SVGElement&&a instanceof n.SVGElement)&&(b=a.parentElement))return b;b=a.parentNode;return ca(b)&&1==b.nodeType?b:null},jd=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document},kd={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},ld={IMG:" ",BR:"\n"},nd=function(a){if(ed&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");
else{var b=[];md(a,b,!0);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");ed||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a},md=function(a,b,c){if(!(a.nodeName in kd))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in ld)b.push(ld[a.nodeName]);else for(a=a.firstChild;a;)md(a,b,c),a=a.nextSibling},od=function(a){this.a=a||n.document||document};od.prototype.getChildren=hd;
var pd=function(a){var b;do b=a,a=-1!=a.indexOf("&")?"document"in n?na(a):oa(a):a;while(a!=b);return a};var qd=function(){this.a=["ad","advertisement","ads","sponsor","sponsored"]};qd.prototype.filter=function(a){for(;a;){var b;a.classList?b=a.classList:(b=a.className,b=u(b)&&b.match(/\S+/g)||[]);for(var c=0;c<b.length;++c)for(var d=b[c].split(/\W+/),e=0;e<d.length;++e)if(0<=ua(this.a,d[e].toLowerCase()))return!1;a=id(a)}return!0};
var rd=function(a){z.call(this);this.g=a;this.a={};this.d={}};y(rd,z);rd.prototype.v=function(){this.unlisten();rd.A.v.call(this)};rd.prototype.listen=function(a,b){var c=w(b,this.g);a.addListener(c);var d=fa(a);d in this.a?this.d[d].add(c):(this.a[d]=a,this.d[d]=new Pb([c]));return this};rd.prototype.unlisten=function(a){if(a){var b=fa(a);if(b in this.a){var c=this.d[b].m();va(c,a.removeListener,a);delete this.d[b];delete this.a[b]}}else Da(this.a,this.unlisten,this)};
var sd=function(){T.call(this);this.h=new U(this);ja(this,ia(ka,this.h))};y(sd,T);sd.prototype.d=function(a){this.g=a};var td=function(a){this.a=a},ud=function(a,b){return a==b?0:a.a-b.a};var vd=function(){this.a=[]};vd.prototype.filter=function(a){for(var b=0;b<this.a.length;++b)if(!this.a[b].filter(a))return!1;return!0};var wd=function(a,b){var c=a.c(b);if(0==c.length)return null;for(var d=c[0],e=1;e<c.length;++e){var f=c[e];f.a>d.a&&(d=f)}return d};vd.prototype.c=function(a){return X(this,a.getElementsByTagName("*"))};var X=function(a,b,c){for(var d=[],e=b.length,f=0;f<e;++f){var g=a.d(b[f],c);g&&d.push(g)}return d};vd.prototype.d=function(){return null};
var xd=function(a,b,c,d){this.a=a;this.c=b;this.d=c;this.e=d};y(xd,td);var Y=function(a,b){var c=jd(a);return c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,null))?c[b]||c.getPropertyValue(b)||"":""},yd=function(a){var b;try{b=a.getBoundingClientRect()}catch(c){return{left:0,top:0,right:0,bottom:0}}M&&a.ownerDocument.body&&(a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop);return b},Ad=function(a){var b=zd;if("none"!=(Y(a,"display")||(a.currentStyle?a.currentStyle.display:
null)||a.style&&a.style.display))return b(a);var c=a.style,d=c.display,e=c.visibility,f=c.position;c.visibility="hidden";c.position="absolute";c.display="inline";a=b(a);c.display=d;c.position=f;c.visibility=e;return a},zd=function(a){var b=a.offsetWidth,c=a.offsetHeight,d=eb&&!b&&!c;return(void 0===b||d)&&a.getBoundingClientRect?(a=yd(a),new V(a.right-a.left,a.bottom-a.top)):new V(b,c)};
var Bd=function(){};Bd.prototype.filter=function(a){for(;a;){if("none"==Y(a,"display"))return!1;var b=Ad(a);if("hidden"==Y(a,"overflow")&&b.D()||"hidden"==Y(a,"visibility"))return!1;a=id(a)}return!0};var Cd=function(){this.a=[];this.a.push(new qd);this.a.push(new Bd)};y(Cd,vd);p(Cd);var Dd=S("image.collections.extension.DocumentImageExtractor"),Ed={".gif":.5},Fd=function(){this.O=0;this.L={}};Cd.prototype.c=function(a){return X(this,a.getElementsByTagName("*"),new Fd)};
Cd.prototype.d=function(a,b){var c=null;switch(a.tagName.toLowerCase()){case "meta":c=Gd(a,1,"property","og:image","content")||Gd(a,.9,"name","msapplication-tileimage","content")||Gd(a,.8,"name","twitter:image","content")||Hd(a);break;case "link":c=Gd(a,.7,"rel","apple-touch-icon","href")||Gd(a,.6,"rel","image_src","href")||Hd(a);break;case "img":if(this.filter(a))a:{if((c=a.src)&&0!=c.lastIndexOf("data:",0)){var d=new V(a.naturalWidth,a.naturalHeight),e=Ad(a),f=Vc(d)<Vc(e)?d:e;if(f.width&&f.height){f=
Id(a);c=new xd(f,c,d,e);break a}}c=null}break;default:if(this.filter(a)&&30>b.O){a:{c=Y(a,"background-image");d=Y(a,"background-repeat");e=Y(a,"background-size");if(d=c&&("no-repeat"==d||"cover"==e)&&0==c.lastIndexOf("url(",0))d=c.length-1,d=0<=d&&c.indexOf(")",d)==d;if(d&&(c=c.substr(4,c.length-5))&&0!=c.lastIndexOf("data:",0)&&(d=Ad(a),d.width&&d.height)){for(var e=Id(a),f=hd(a),g=0;g<f.length;++g){var h=f[g];if("none"!=Y(h,"display")&&Vc(Ad(h))>.1*Vc(d)){e*=.1;break}}c=new xd(e,c,void 0,d);break a}c=
null}c&&++b.O}}if(!c)return null;e=c.e||c.d;if(c.c!=document.location.href&&(100>e.width||100>e.height))return null;d=c.a;d/=1+Math.exp(-1E-5*Vc(e));e=e.width/e.height;1>e&&(e=1/e);2<e&&(d*=.8);e=c.c;try{var k=jd(a).documentURI,f=e;k instanceof P||(k=Ib(k));f instanceof P||(f=Ib(f));var g=k,k=f,q=g.clone(),m=!!k.d;m?xb(q,k.d):m=!!k.i;m?q.i=k.i:m=!!k.c;m?q.c=k.c:m=null!=k.k;var t=k.a;if(m)yb(q,k.k);else if(m=!!k.a){if("/"!=t.charAt(0))if(g.c&&!g.a)t="/"+t;else{var v=q.a.lastIndexOf("/");-1!=v&&(t=
q.a.substr(0,v+1)+t)}v=t;if(".."==v||"."==v)t="";else if(-1!=v.indexOf("./")||-1!=v.indexOf("/.")){for(var ac=0==v.lastIndexOf("/",0),hb=v.split("/"),v=[],f=0;f<hb.length;){var bc=hb[f++];"."==bc?ac&&f==hb.length&&v.push(""):".."==bc?((1<v.length||1==v.length&&""!=v[0])&&v.pop(),ac&&f==hb.length&&v.push("")):(v.push(bc),ac=!0)}t=v.join("/")}else t=v}m?q.a=t:m=""!==k.h.toString();m?zb(q,Ab(k.h.toString())):m=!!k.e;m&&(q.e=k.e);e=q.toString()}catch(oe){return Dd&&Dd.log(Yb,"Cannot resolve url: "+e,
void 0),null}q=B(pb(qb(e)[5]||null));m=q.lastIndexOf(".");0<m&&(q=Ed[q.slice(m)])&&(d*=q);if(e in b.L&&b.L[e]>d)return null;b.L[e]=d;return new xd(d,e,c.d,c.e)};
var Gd=function(a,b,c,d,e){if(B(a.getAttribute(c)).toLowerCase()==d.toLowerCase()){c=a.getAttribute(e);if(!c||0==c.lastIndexOf("data:",0))return null;d=qa(a.getAttribute("data-google-stars-image-width"));e=qa(a.getAttribute("data-google-stars-image-height"));if(d&&e)return a=jd(a),"/"!=pb(qb(a.documentURI)[5]||null)&&-1==a.body.innerHTML.indexOf(c)&&(b*=.5),new xd(b,c,new V(d,e))}return null},Hd=function(a){var b=a.getAttribute("itemprop");if(b&&"thumbnailurl"==b.toLowerCase()){b=a.getAttribute("href")||
a.getAttribute("content");if(!b||0==b.lastIndexOf("data:",0))return null;var c=qa(a.getAttribute("data-google-stars-image-width"));a=qa(a.getAttribute("data-google-stars-image-height"));if(c&&a)return new xd(.55,b,new V(c,a))}return null},Id=function(a){var b=jd(a),c=new gd(0,0),d;d=b?jd(b):document;var e;(e=!M||M&&(L()||9<=mb))||(e="CSS1Compat"==(d?new od(jd(d)):ta||(ta=new od)).a.compatMode);a!=(e?d.documentElement:d.body)&&(a=yd(a),d=(b?new od(jd(b)):ta||(ta=new od)).a,b=eb||"CSS1Compat"!=d.compatMode?
d.body||d.documentElement:d.documentElement,d=d.parentWindow||d.defaultView,b=M&&N("10")&&d.pageYOffset!=b.scrollTop?new gd(b.scrollLeft,b.scrollTop):new gd(d.pageXOffset||b.scrollLeft,d.pageYOffset||b.scrollTop),c.x=a.left+b.x,c.y=a.top+b.y);c=c.y;return 2E3<c?0:1/(1+Math.exp(.001*c))};
var Jd=function(a,b){this.a=a;this.c=b};y(Jd,td);var Kd=function(){this.a=[]};y(Kd,vd);p(Kd);Kd.prototype.c=function(a){var b=X(this,a.getElementsByTagName("meta"));b.push(Ld(a));if(a=a?a.parentWindow||a.defaultView:window)a=a.getSelection().toString(),0<a.length&&b.push(new Jd(1,a));return b};
Kd.prototype.d=function(a){var b=0,c="";switch(a.tagName.toLowerCase()){case "meta":var d=a.getAttribute("name"),e=a.getAttribute("property");if(e&&"og:description"==e.toLowerCase())b=.9;else if(d)switch(d.toLowerCase()){case "twitter:description":b=.8;break;case "description":b=.7;break;case "msapplication-tooltip":b=.6}0<b&&(c=a.getAttribute("content")||"")}c=pd(c);a=document.createElement("div");a.innerHTML=c;c=a.textContent;c=c.trim();return 5<c.length?(1024<c.length&&(c=c.substring(0,1021)+"..."),
new Jd(b,c)):null};
var Ld=function(a){if(a.body){var b="",c="",d=0;a=a.body.innerText.replace(/(\r\n|\r|\n)/g,"\n");for(var e=a.split("\n"),f=0;f<e.length;++f){for(var b=e[f].replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,""),g=b.split(" "),h=g.length,k,q=k=0;q<b.length;++q)!/[^a-zA-Z]/.test(b.charAt(q))&&++k;if(q=64<=b.length&&8<=h&&k>=.4*b.length){for(var m=q=0;m<b.length;++m){var t=b.charAt(m);/[^a-zA-Z0-9]/.test(t)&&/[^\t\n\r ]/.test(t)&&++q}q=0<q}if(q&&24>=Md(g))break;k>=.4*b.length&&h>d&&24>=Md(g)&&(c=b,d=h); b=""}0==b.length&&20<c.length&&4<=d&&(b=c);a=a.replace(/[\t\r\n ]+/g," ").replace(/^[\t\r\n ]+|[\t\r\n ]+$/g,"");return new Jd(.1,b||a.substring(0,1024))}return null},Md=function(a){for(var b=0,c=0;c<a.length;++c)b=Math.max(a[c].length,b);return b};
var Nd=function(a,b){this.a=a;this.c=b};y(Nd,td);var Od=function(a){return a.c};var Pd=function(a,b,c){this.a=a;this.d=b;this.c=c};y(Pd,td);var Qd=function(a,b,c,d){this.d=a;this.a=b;this.c=c;this.e=d};Qd.prototype.getTitle=function(){return this.d};var Rd=function(){this.a=[]};y(Rd,vd);p(Rd);Rd.prototype.c=function(a){var b=X(this,a.getElementsByTagName("meta")).concat(X(this,a.getElementsByTagName("title"))),c=X(this,a.getElementsByTagName("h1"));0<c.length?1==c.length&&(b=ya(b,c)):(c=X(this,a.getElementsByTagName("h2")),0<c.length?1==c.length&&(b=ya(b,c)):(c=X(this,a.getElementsByTagName("h3")),0<c.length&&1==c.length&&(b=ya(b,c))));a.title&&b.push(new Nd(1,a.title));b.push(new Nd(.1,a.documentURI));return b};
Rd.prototype.d=function(a){var b=0,c="";switch(a.tagName.toLowerCase()){case "title":b=.5;c=nd(a);break;case "h1":b=.4;c=nd(a);break;case "h2":b=.3;c=nd(a);break;case "h3":b=.2;c=nd(a);break;case "meta":var d=a.getAttribute("name"),e=a.getAttribute("property");if(e&&"og:title"==e.toLowerCase())b=.9;else if(d)switch(d.toLowerCase()){case "application-name":b=.8;break;case "twitter:title":b=.7;break;case "title":b=.6}0<b&&(c=a.getAttribute("content")||"")}c=pd(c.trim());return 1<c.length?new Nd(b,c): null};
var Sd=function(){this.a=[]};y(Sd,vd);p(Sd);Sd.prototype.d=function(a){switch(a.tagName.toLowerCase()){case "meta":var b;a:{if("og:video"==B(a.getAttribute("property")).toLowerCase()){b=a.getAttribute("content");var c=qa(a.getAttribute("data-google-stars-video-width"));a=qa(a.getAttribute("data-google-stars-video-height"));if(b&&0<c&&0<a){b=new Pd(1,b,new V(c,a));break a}}b=null}return b}return null};
var Td=function(a,b,c,d){this.d=a||Rd.p();this.c=b||Kd.p();this.a=c||Cd.p();this.e=d||Sd.p()};p(Td);var Ud=function(){var a=Td.p(),b=document,c=wd(a.d,b),d=wd(a.c,b),e=a.a.c(b),a=wd(a.e,b);Aa(e,function(a){return a.c});return new Qd(c,d,e,a)};var Vd=function(){sd.call(this);this.a=null;this.i=new rd(this);ja(this,ia(ka,this.i))};y(Vd,sd);var Wd=S("image.collections.extension.ContentController");Vd.prototype.d=function(a){Vd.A.d.call(this,a);this.i.listen(chrome.runtime.onMessage,this.K)};
Vd.prototype.K=function(a,b,c){c({received:"true"});switch(a.type){case "collect_page":if(null===this.a){b=a.clipId;c=a.userId;a=new Pa;G(a,1,b);G(a,2,c);b=new Ua;I(b,1,a);a=x();G(b,7,a);G(b,8,a);this.a=new W(b);b=document.documentURI;/\.(jpg|jpeg|png|gif|bmp|svg|tiff)$/i.test(b)?cd(this.a,1):cd(this.a,2);a=new Mb;try{Ib(b)}catch(d){b=encodeURI(b)}try{Ib(b)}catch(e){b=""}G(a.a,3,b);b=this.a;b.h=a;I(b.a,6,a.a);Xd(this,!0)}else Wd&&Wd.log(Xb,"Clip is already being created",void 0);break;case "get_salient_images":Xd(this,
!1);break;default:Wd&&Wd.log(Wb,"Invalid message type: "+a.type,void 0)}};var Xd=function(a,b){var c=w(a.k,a,b);Uc(a.h,a.g,"dom_initialized",c,void 0);a.s("initialize_dom")};
Vd.prototype.k=function(a){var b=Ud(),c=b.c;c.sort(ud||Ba);for(var d=[],e=null,f=0;f<c.length;f++){var g=e=new Wc,h=c[f].c;g.c=null;try{var k=J(g.a);G(k,1,h);g.c=new P(B(Oa(J(g.a))))}catch(q){h=J(g.a),G(h,1,void 0),h=J(g.a),G(h,2,void 0),h=J(g.a),G(h,3,void 0)}g.c&&F(g.a,6)&&G(g.a,6,!1);var m=c[f].d;if(m){var g=e,h=m.width,m=m.height,t=J(g.a);G(t,2,h);g=J(g.a);G(g,3,m)}d.unshift(e.l())}if(a){!ad(this.a)&&e&&(a=this.a,c=e,a.d=c,I(a.a,5,c.a),c=x(),G(a.a,8,c));a=bd(this.a);!a.getTitle()&&b.getTitle()&&
a.setTitle(Od(b.getTitle()));!B(F(a.a,2))&&b.a&&G(a.a,2,b.a.c);if(a=b.e)cd(this.a,4),b=new Yc,G(b.a,1,a.d),c=a.c.height,G(b.a,2,a.c.width),G(b.a,3,c),a=this.a,a.i=b,I(a.a,10,b.a);chrome.runtime.sendMessage({type:"created_clip",clipData:this.a.l(),images:d});this.a=null}else chrome.runtime.sendMessage({type:"salient_images_found",images:d})};
var Z=function(){sd.call(this);this.a=0;this.i=-1};y(Z,sd);var Yd=S("image.collections.extension.DomController");Z.prototype.d=function(a){Z.A.d.call(this,a);this.h.listen(a,"initialize_dom",this.K)};
Z.prototype.K=function(){if(0==this.a){var a=document,b=a.getElementsByTagName("meta"),a=a.getElementsByTagName("link");this.a=b.length+a.length;if(0<this.a){va(b,this.T,this);va(a,this.S,this);b=w(this.s,this,"dom_initialized");if(!ba(b))if(b&&"function"==typeof b.handleEvent)b=w(b.handleEvent,b);else throw Error("Invalid listener argument");this.i=n.setTimeout(b,5E3)}else this.s("dom_initialized")}};
Z.prototype.T=function(a){var b="";if(a.hasAttribute("property"))switch(a.getAttribute("property").toLowerCase()){case "og:image":var b=a.getAttribute("content"),c=hd(id(a)),d=Zd(c,"og:image:width"),c=Zd(c,"og:image:height");0<d&&0<c&&(a.setAttribute("data-google-stars-image-width",d),a.setAttribute("data-google-stars-image-height",c));break;case "og:video":c=hd(id(a)),d=Zd(c,"og:video:width"),c=Zd(c,"og:video:height"),0<d&&0<c&&(a.setAttribute("data-google-stars-video-width",d),a.setAttribute("data-google-stars-video-height",
c))}else if(a.hasAttribute("name"))switch(a.getAttribute("name").toLowerCase()){case "msapplication-tileimage":case "twitter:image":b=a.getAttribute("content")}else if(a.hasAttribute("itemprop"))switch(a.getAttribute("itemprop").toLowerCase()){case "thumbnailurl":b=a.getAttribute("href")||a.getAttribute("content")}$d(this,b,a)};
Z.prototype.S=function(a){var b="";if(a.hasAttribute("rel"))switch(a.getAttribute("rel").toLowerCase()){case "apple-touch-icon-precomposed":case "apple-touch-icon":case "image_src":b=a.getAttribute("href")}else if(a.hasAttribute("itemprop"))switch(a.getAttribute("itemprop").toLowerCase()){case "thumbnailurl":b=a.getAttribute("href")||a.getAttribute("content")}$d(this,b,a)};
var Zd=function(a,b){for(var c=0;c<a.length;++c){var d=a[c];if(d.hasAttribute("property")&&d.getAttribute("property").toLowerCase()==b&&d.hasAttribute("content"))return d.getAttribute("content")}return""},$d=function(a,b,c){if(!b||c.hasAttribute("data-google-stars-image-width")&&c.hasAttribute("data-google-stars-image-height"))ae(a);else{var d=w(a.U,a,c);c=new Image;d=w(a.k,a,d);Uc(a.h,c,["load","error"],d,void 0);c.src=b}};
Z.prototype.k=function(a,b){var c=b.target;"load"==b.type?a(c.naturalWidth,c.naturalHeight):Yd&&Yd.log(Xb,"Failed to load image "+c.src,void 0);ae(this)};var ae=function(a){0==--a.a&&(-1!=a.i&&(n.clearTimeout(a.i),a.i=-1),a.s("dom_initialized"))};Z.prototype.U=function(a,b,c){a.setAttribute("data-google-stars-image-width",b);a.setAttribute("data-google-stars-image-height",c)};
var be=function(){this.a=x()},ce=new be;be.prototype.set=function(a){this.a=a};be.prototype.reset=function(){this.set(x())};be.prototype.get=function(){return this.a};var de=function(a){this.e=a||"";this.g=ce};de.prototype.a=!0;de.prototype.c=!0;de.prototype.d=!1;var ee=function(a){return 10>a?"0"+a:String(a)},fe=function(a,b){var c=(a.d-b)/1E3,d=c.toFixed(3),e=0;if(1>c)e=2;else for(;100>c;)e++,c*=10;for(;0<e--;)d=" "+d;return d},ge=function(a){de.call(this,a)};y(ge,de);
var he=function(){w(this.e,this);this.a=new ge;this.a.c=!1;this.a.d=!1;this.c=this.a.a=!1;this.d="";this.g={}};
he.prototype.e=function(a){if(!this.g[a.c]){var b;b=this.a;var c=[];c.push(b.e," ");if(b.c){var d=new Date(a.d);c.push("[",ee(d.getFullYear()-2E3)+ee(d.getMonth()+1)+ee(d.getDate())+" "+ee(d.getHours())+":"+ee(d.getMinutes())+":"+ee(d.getSeconds())+"."+ee(Math.floor(d.getMilliseconds()/10)),"] ")}c.push("[",fe(a,b.g.get()),"s] ");c.push("[",a.c,"] ");c.push(a.getMessage());b.d&&(d=a.a)&&c.push("\n",d instanceof Error?d.message:d.toString());b.a&&c.push("\n");b=c.join("");if(c=ie)switch(a.e){case Vb:je(c, "info",b);break;case Wb:je(c,"error",b);break;case Xb:je(c,"warn",b);break;default:je(c,"debug",b)}else this.d+=b}};var ie=n.console,je=function(a,b,c){if(a[b])a[b](c);else a.log(c)};
var ke=function(){T.call(this);this.d=new Z;ja(this,ia(ka,this.d));this.a=new Vd;ja(this,ia(ka,this.a))};y(ke,T);p(ke);var le=new he;0!=le.c&&(ec(),le.c=!1);var me=S("image.collections.extension.Content"),ne=ke.p();me&&me.log(Yb,"Initializing extension content",void 0);ne.d.d(ne);ne.a.d(ne);window.full_script_injected=!0;

}catch(e){_DumpException(e)}
// Google Inc.
