var CPWbatch,g_batchpagealive=!0,g_batchpagealiveinterval=-1;CPWbatch||(CPWbatch=new CPWbatch_lib);var g_cpw_batch_aid=null,g_cpw_aid_queue=[],g_cpw_batch_last_start_ts=0,g_cpw_status_update_lastmsg="",F_OK=1,F_FAIL=2,F_TIMEOUT=4,F_PENDING=8,F_ALL=F_OK|F_FAIL|F_TIMEOUT|F_PENDING,P_RESET=!0,F_STARTED="started",F_DONE="done",F_NONE=null;function close_cpw_tabs(){g_ischrome&&chrome.tabs.getSelected(function(a){cpwbot_close_cpw_tab_handler(a)})}
function cpwbot_close_cpw_tab_handler(a){var e=gettabid(a);if(null!==g_cpw_server_initiated_tabid&&null!==a&&(e==CPWbot_bg.originating_tabid||e==CPWbot_bg.destination_tabid))if(g_ischrome)chrome.tabs.update(g_cpw_server_initiated_tabid,{active:!0});else if(g_issafari)(a=g_CS_tabs[g_cpw_server_initiated_tabid])&&a.activate();else if(g_isopera)(a=g_CS_tabs[g_cpw_server_initiated_tabid])&&a.update({selected:!0});else if(!g_ismaxthon)if(g_isfirefoxsdk)for(a=0;a<g_tabs.length;a++){if(g_tabs[a].id==g_cpw_server_initiated_tabid){g_tabs[a].activate();
break}}else g_isfirefox&&activate_tabid(g_cpw_server_initiated_tabid);if(CPWbot_bg){if(null!==CPWbot_bg.originating_tabid)if(g_ischrome)"undefined"!=typeof chrome.tabs.remove&&chrome.tabs.remove(CPWbot_bg.originating_tabid,function(){});else if((g_issafari||g_isopera)&&null!==g_CS_tabs)(a=g_CS_tabs[CPWbot_bg.originating_tabid])&&a.close();else if(!g_ismaxthon)if(g_isfirefoxsdk)for(a=0;a<g_tabs.length;a++){if(g_tabs[a].id==CPWbot_bg.originating_tabid){g_tabs[a].close();break}}else g_isfirefox&&close_tabid(CPWbot_bg.originating_tabid);
if(null!==CPWbot_bg.destination_tabid)if(CPWbatch&&CPWbatch.deregister_worker(CPWbot_bg.destination_tabid),g_ischrome)"undefined"!=typeof chrome.tabs.remove&&chrome.tabs.remove(CPWbot_bg.destination_tabid,function(){chrome.runtime.lastError&&debug&&L(chrome.runtime.lastError)});else if((g_issafari||g_isopera)&&null!==g_CS_tabs)(a=g_CS_tabs[CPWbot_bg.destination_tabid])&&a.close();else if(!g_ismaxthon)if(g_isfirefoxsdk)for(a=0;a<g_tabs.length;a++){if(g_tabs[a].id==CPWbot_bg.destination_tabid){g_tabs[a].close();
break}}else g_isfirefox&&close_tabid(CPWbot_bg.destination_tabid)}}function start_pwchange_from_server(a,e){debug&&L("running start_pwchange_from_server for aid="+e+" batchstate="+CPWbatch.cpw_get_batchjob_state());CPWbatch&&CPWbatch.cpw_get_batchjob_state()&&(g_cpw_batch_last_start_ts=(new Date).getTime());cpwbot_preinit();return dopwchange(e,!0,null,!0)}
function end_pwchange_from_server(a,e){var c=cpwbot_getpwchangestate();"FAIL"!=c&&("CAPTCHA"!=c&&"DONE"!=c&&"OK"!=c&&"TIMEOUT"!=c&&0!=c&&null!==c)&&(CPWbatch&&CPWbatch.cpw_get_batchjob_state()?e==that.getpwchangeaid()?(L("halting for aid="+e+" current_state="+c),cpwbot_halt()):pass:cpwbot_halt());g_isfirefox?cpwbot_close_cpw_tab_handler(LP.mostRecent().getBrowser().selectedTab):get_selected_tab(null,function(c){cpwbot_close_cpw_tab_handler(c)})}
function CPWbatch_lib(){function a(){}function e(b){return"undefined"!=typeof g_sites?g_sites[b]:"undefined"!=typeof lpaccts?lpaccts[b]:null}var c=this,g={},l=null,j=null,d={};this.register_worker=function(b,h){if(null===g||!b)return!1;var a=b.toString();if(1<=c.count_workers())return L("too many workers, "+c.count_workers()+" >= 1"),!1;L("registered: worker "+a+" aid="+h);g[a]=h;c.cpw_batchjob_mark_stats(F_PENDING);return!0};this.count_workers=function(){if(null===g)return-1;var b=0,h;for(h in g)g.hasOwnProperty(h)&&
b++;return b};this.deregister_worker=function(b){if(null===g||!b)return!1;b=b.toString();g[b]&&(L("deregistered: worker "+b+" from aid="+g[b]),delete g[b]);c.cpw_batchjob_mark_stats(F_PENDING);return!0};this.logout=function(){g=[];c.cpw_batchjob_reset_stats();j=null};this.init=function(){g=[];c.cpw_batchjob_reset_stats();j=null};this.cpw_batchjob_mark_stats=function(b,h){if(!d)return!1;var a=null,f=null;h&&h.aid&&(f=h.aid);h&&h.reset&&(a=h.reset);if(0===(b&F_ALL))return!1;(b&F_OK)==F_OK&&("undefined"!=
typeof a&&a?d.ok=0:d.ok++);(b&F_FAIL)==F_FAIL&&("undefined"!=typeof a&&a?d.fail=0:d.fail++);(b&F_TIMEOUT)==F_TIMEOUT&&("undefined"!=typeof a&&a?d.timeout=0:d.timeout++);(b&F_PENDING)==F_PENDING&&(d.pending="undefined"!=typeof a&&a?0:c.count_workers());"undefined"==typeof d.byaid&&(d.byaid={});f&&("undefined"!=typeof a&&a?delete d.byaid[f.toString()]:d.byaid[f.toString()]=b);return!0};this.cpw_batchjob_reset_stats=function(){d=null;d=new a;if(!d)return!1;c.cpw_batchjob_mark_stats(F_ALL,{reset:P_RESET});
if("undefined"==typeof Date)return!1;var b=(new Date).getTime();d.start_time=b;return!0};this.cpw_batchjob_endjob_stats=function(){if(!d)return!1;var b=(new Date).getTime(),a=b-d.start_time;d.end_time=b;d.elapsed=a;return!0};this.cpw_batchjob_getstats=function(){return d};this.cpw_get_batchjob_state=function(){return j};this.cpw_set_batchjob_state=function(b){if("undefined"==typeof b)return debug&&L("batchjob state is missing"),!1;j=b;return!0};this.cpw_queue_change_donext=function(){var b=c.cpw_queue_change_getnext();
g_cpw_batch_aid=b;if(null!=b){if(start_pwchange_from_server(g_cpw_server_initiated_tabid,b))return b;CPWbatch.cpw_batchjob_mark_stats(F_FAIL,{aid:b});var a="failed to initiate pw change in batch job for aid="+b;c.conditional_website_status_update({aid:b,msg:a});console_error(a);if(lploggedin&&!e(b))return verbose_log("bad aid="+b+" proceed to next"),c.cpw_queue_change_donext();if(lploggedin&&e(b))return verbose_log("other error for aid="+b+" proceed to next"),c.cpw_queue_change_donext()}setTimeout(function(){c.cpw_batch_end()},
0);return null};this.cpw_queue_change_getnext=function(){return!g_cpw_aid_queue||0>=g_cpw_aid_queue.length?null:g_cpw_aid_queue.shift()};this.cpw_batch_end=function(){CPWbatch&&(c.cpw_set_batchjob_state(F_DONE),g_cpw_aid_queue=[],clearInterval(g_batchpagealiveinterval),g_cpw_batch_aid=null,CPWbatch&&(c.cpw_batchjob_endjob_stats(),c.cpw_batchjob_mark_stats(F_PENDING)),c.conditional_website_status_update({msg:"done"}))};this.cpw_queue_push=function(b){if("undefined"==typeof b||null===b||isNaN(b))return!1;
g_cpw_aid_queue.push(b);return!0};this.cpw_batch_wait=function(b){if(CPWbatch){var a=!1,d=!1,f=g_cpw_batch_aid,e=cpwbot_getpwchangestate();L(sprintf("cpw_batch_wait wake up, state=%s batchstate=%s aid=%d\n",e,CPWbatch.cpw_get_batchjob_state(),f));CPWbatch.cpw_get_batchjob_state()==F_DONE&&(a=!0);switch(e){case "TIMEOUT":case "CAPTCHA":case "FAIL":case "FAIL_PW_SAVED":d=a=!0;break;case "OK":case "DONE":a=!0;break;case "preinit":case null:CPWbot_bg.get_failstate()&&(d=a=!0)}var g=(new Date).getTime();
0<g_cpw_batch_last_start_ts&&(3E5<g-g_cpw_batch_last_start_ts&&CPWbatch.cpw_get_batchjob_state()!=F_DONE)&&!a&&(d=a=!0,e="TIMEOUT",L("BATCH JOB TIMED OUT"),CPWbatch.cpw_set_batchjob_state(F_DONE));if(a){d?"TIMEOUT"==e?CPWbatch.cpw_batchjob_mark_stats(F_TIMEOUT,{aid:f}):CPWbatch.cpw_batchjob_mark_stats(F_FAIL,{aid:f}):CPWbatch.cpw_batchjob_mark_stats(F_OK,{aid:f});CPWbatch.cpw_batchjob_mark_stats(F_PENDING);if(CPWbatch.cpw_get_batchjob_state()==F_DONE)return;end_pwchange_from_server(g_cpw_server_initiated_tabid,
f);c.conditional_website_status_update({aid:f,msg:"finished change on "+f+" in current batchjob"});b()}else pass;setTimeout(function(){c.cpw_batch_wait(b)},1001)}};this.cpw_batch_begin=function(b){c.cpw_reset_status_update_ack();g_cpw_status_update_lastmsg="";c.init();var a=!1,d;for(d in g_cpw_aid_queue){var f=g_cpw_aid_queue[d];g_cpw_aid_queue.hasOwnProperty(d)&&e(f)&&e(f).pwprotect&&(a=!0)}!b&&a?security_prompt(function(){CPWbatch.cpw_batch_begin(!0)}):(g_batchpagealiveinterval=setInterval(function(){g_batchpagealive?
(console.error("heartbeat received. setting to false"),g_batchpagealive=!1):(console.error("Killing the batch update. No heartbeat received."),g_cpw_aid_queue=[],cpwbot_halt())},3E4),c.cpw_batchjob_reset_stats(),c.cpw_set_batchjob_state(F_STARTED),g_cpw_batch_aid=c.cpw_queue_change_donext(),setTimeout(function(){c.cpw_batch_wait(c.cpw_queue_change_donext)},1001))};this.conditional_website_status_update=function(b){if(g_cpw_server_initiated_tabid){b||(b={});var a=b.msg;"undefined"==typeof a&&(a="");
var d=b.aid;"undefined"==typeof d&&(d=CPWbot_bg.getpwchangeaid());var f=b.state;"undefined"==typeof f&&(f=cpwbot_getpwchangestate());b=b.batchstate;"undefined"==typeof b&&(b=CPWbatch.cpw_get_batchjob_state());var e;if(null!==b&&CPWbatch){CPWbatch.cpw_batchjob_mark_stats(F_PENDING);try{e=LPJSON.stringify(CPWbatch.cpw_batchjob_getstats())}catch(g){var k="JSON error: "+g;CPWbot_bg&&CPWbot_bg.warning_phone_home(k);console_error(k)}}else e=LPJSON.stringify(CPWbot_bg.get_timestamps());if(CPWbot_bg&&null===
CPWbot_bg.originating_tabid&&null===CPWbot_bg.originating_tab&&null!==g_cpw_server_initiated_tabid&&null!==CPWbot_bg.destination_tabid&&null!==CPWbot_bg.destination_tab)if(k="",g_isdebug&&(k=CPWbot_bg.get_user_debug_messages()),CPWbatch.cpw_get_batchjob_state()){if(!l){var j=g_cpw_status_update_lastmsg;a!=j&&(a=j+"\n"+a);g_cpw_status_update_lastmsg=a}g_cpw_status_update_lastmsg=a;c.cpw_clear_status_update_ack();a=JSON.stringify({aid:d,state:f,msg:a,debugmsg:k});sendCS(g_cpw_server_initiated_tabid,
{cmd:"cpw_batch_status_update",msgstr:a,batchstate:b,stats:e})}else sendCS(g_cpw_server_initiated_tabid,{cmd:"cpw_status_update",state:f,msg:a,debugmsg:k,aid:d,batchstate:b,stats:e})}};this.cpw_set_status_update_ack=function(a){l=a};this.cpw_get_status_update_ack=function(){return l};this.cpw_clear_status_update_ack=function(){c.cpw_set_status_update_ack(!1)};this.cpw_reset_status_update_ack=function(){l=null}};
